### ISSUE TITLE
mmlink bug: No hardware found in Signal Tap Logic Analyzer, although System Console shows 'Remote system ready'

### ISSUE THREAD

**Issue by griffin-warrior** [OFS/opae-sdk#1190]
At first, I succeed to connect the remote debug target, the PAC host through mmlink according to the instructions in the AFU design guide.  For whatever reason, it doesn't work today. I have tried to connect on Linux, Windows, putty ssh tunnel, and reboot... It still doesn't work. So I suppose there is something wrong on the PAC host. However, I can't find any documents or threads discussing debugging SigalTap connection through mmlink.
Do the two warnings in the System Console mean anything?
"Could not register IService packet."
"A service named 'packet' is already registered."
I am sure my operation is correct. What is the problem?

BTW, can I use SignalTap on the PAC host without connecting mmlink? It seems that the GBS with .stp inside only support connection through mmlink.
![mmlink_failure](https://user-images.githubusercontent.com/29499271/53861125-2aa28000-401e-11e9-93a1-e19bca41f418.png)

**Comment by eyeloveu** [comment]
Something wired just happened. I tried to power off the PAC host and then power it on. It worked! But only once. After I quit mmlink, it never worked again even though I powered off and on several times.

**Comment by eyeloveu** [comment]
Some environment information：
Ubuntu 16.04
-           OPAE: 1.1.2                      -
-            BBB: 1.3.0-1                    -
-       PLATFORM: a10_gx_pac_ias_1_2_pv    
-     QURTUS_PRO: 17.1.1.273
