### ISSUE TITLE
ASE Scripts rely on $QUARTUS_HOME environment variable, should use $QUARTUS_ROOTDIR

### ISSUE THREAD

**Issue by mdbtucker** [OFS/opae-sdk#2952]
ASE scripts are relying on QUARTUS_HOME, which I think is obsolete, they should be using QUARTUS_ROOTDIR (which I've been told you can rely on being set if Quartus is installed.  Probably worth double checking that, but certainly it's set with any ACDS ARC resource you grab).

The ask is to remove all references to QUARTUS_HOME in any ASE/OPAE scrips, and replace them with references to QUARTUS_ROOTDIR.  The documentation should then also be updated.

**Comment by aditikum** [comment]
This looks like an update will be needed, we'll be working on the update for main

**Comment by mdbtucker** [comment]
Any progress or ETA on this?

**Comment by sophimao** [comment]
Currently I plan to complete this by OFS2023.2 CC, I'll update if there is any change.
