### ISSUE TITLE
Not able to test 10/100G HSSI AFUs on N5014 cards

### ISSUE THREAD

**Issue by ehabosaleh** [OFS/opae-sdk#3012]
I'm trying to test sending and receiving packets through one of the hssi interfaces on the N5014 card. However, every time I run hssi, I get the same error ([error] no accelerator found with id: 823c334c-98bf-11ea-bb37-0242ac130002). 

Is this the default id, and do I need to modify the source code with the N5014 GUID and rebuild opae to use hssi testing modes on N5014 cards?

**Comment by rchriste1** [comment]
In opae-sdk there are programs like: hssi, hssiloopback, hssimac, hssistats they have been made to work with the HSSI interface on the N61x cards. These programs are based on the uio driver giving generic access to the HSSI interface in these cards and then doing all the handling in user space. These programs do not support N5010, N5011, N5013, and N5014 cards.

The N501x cards use the n5010-hssi driver to provide access to the HSSI functionality. This driver create network interface in Linux named n5010_hssix. Then standard Linux tools like ethtool, ifconfig etc. can be used to see the network interfaces and read statistics. The N5014 card currently only supports 100G.

If you want to send Ethernet traffic from host to the card or receive traffic in host, this is done via the CVL network chips on the card. The CVLs are handled by the standard Intel ICE driver that creates network interface for them.

I suggest you take contact to Silicom Denmark Support at [support@silicom.dk](support@silicom.dk).
Silicom provides a selfinstallable software package with needed kernel drivers, compiled opae-sdk and additional tools. Silicom also provides a N501x User Guide that will guide you through how to use the card.

Regards
Roger Christensen
Senior Software developer
Silicom Denmark A/S
