### ISSUE TITLE
QPAFilter tool and new power analysis tool (quartus_pow ) in Quartus 23.1 Pro

### ISSUE THREAD

**Issue by umairsiddiqui-digitek** [OFS/opae-sdk#3048]
The **quartus_pow** in Quartus 23.1 Pro (&  Quartus 23.2 Pro) don't generate  Power Analysis reports (*.pow.rpt), 

https://github.com/OFS/opae-sdk/blob/d63ca2cdd47c225557c4a63cd14eb2a175d39993/binaries/qpafilter/qpafilter.py#L405C1-L406C1

instead it generates a binary file *.qptc

`quartus_pow ofs_top`

How to generate sensor blob for BMC with new `quartus_pow` tool in Quartus 23.1 Pro

**Comment by tswhison** [comment]
Issue has been triaged and forwarded to Quartus team for assistance.
