### ISSUE TITLE
Integrate hssiloopback and hssistats into hssi

### ISSUE THREAD

**Issue by pcolberg** [OFS/opae-sdk#3118]
From https://github.com/OFS/opae-sdk/pull/3117: While the D5005 FPGA card employs a separate kernel driver (s10hssi) to configure loopback and provide statistics via a network device, newer FPGA cards expose a UIO device used with hssiloopback and hssistats. Can the latter functionality be integrated into the hssi command?

**Comment by nathanborak** [comment]
`hssiloopback` and `hssistats` have both been removed from documentation and users are instructed to use `hssi` instead for PCIe Attach Shell designs on AGX7.
