### ISSUE TITLE
Verification: C/C++ CI Build and Test / build-doc fails after upgrade to use python 3.12

### ISSUE THREAD

**Issue by rchriste1** [OFS/opae-sdk#3127]
See [https://github.com/OFS/opae-sdk/pull/3119 ](https://github.com/OFS/opae-sdk/pull/3119 ) 
A change has been made in python: See PEP 668 for the detailed specification.

**Comment by nathanborak** [comment]
Pull has been merged into OPAE SDK, and we now advocate the use of virtual environments to build OPAE SDK locally. @rchriste1,  do you still wish to keep the issue open?

**Comment by rchriste1** [comment]
The issue was solved, so the ci build could run. Issue can be closed.
